apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'


android {
    //namespace appPackageName
	namespace "com.watabou.pixeldungeon"
    compileSdkVersion appAndroidCompileSDK

    setProperty("archivesBaseName", appVersionName)
    buildFeatures {
        buildConfig = true
    }
    defaultConfig {
        manifestPlaceholders = [appName:appName]
        applicationId appPackageName

        versionCode appVersionCode
        versionName appVersionName

        //noinspection MinSdkTooLow
        minSdkVersion appAndroidMinSDK
        targetSdkVersion appAndroidTargetSDK
    }

}

dependencies {
    implementation project(':PD-classes')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:30.3.1')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.android.gms:play-services-measurement-api:19.0.0'
    implementation "com.github.RohitSurwase.UCE-Handler:uce_handler:1.4"
    // Declare the dependencies for the Crashlytics and Analytics libraries
    // When using the BoM, you don't specify versions in Firebase library dependencies
}
repositories {
    mavenCentral()
}